<?php
# Generated by the protocol buffer compiler (spiral/php-grpc). DO NOT EDIT!
# source: proto/service.proto

namespace Service;

use Spiral\GRPC;

interface GreeterInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "service.Greeter";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param Message $in
    * @return Message
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function sayHello(GRPC\ContextInterface $ctx, Message $in): Message;
}
