<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/service.proto

namespace GPBMetadata\Proto;

class Service
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a7a0a1370726f746f2f736572766963652e70726f746f12077365727669" .
            "636522170a074d657373616765120c0a046e616d6518012001280932390a" .
            "0747726565746572122e0a0873617948656c6c6f12102e73657276696365" .
            "2e4d6573736167651a102e736572766963652e4d65737361676562067072" .
            "6f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

